### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by agkuba** [kostergroup/SIMsalabim#4]
Hello! I just tried compiling the latest versions of SimSS and ZimT  in wsl, and got some errors for both files that prevented the compilation from finishing. Am I doing something wrong or is there an issue in the latest version? Sorry, I'm not super experienced with linux yet!

![image](https://github.com/kostergroup/SIMsalabim/assets/91749272/22d7dc6b-53b8-4496-9b4b-e4d4444fec41)

**Comment by kostergroup** [comment]
Thanks for trying SIMsalabim!
Slightly strange as the compiler should check to see if it's new enough. So normally, I would expect a compiler message stating that the compiler is too old.  It should be at least 3.2.0, whereas yours is 3.0.4+dfsg-23, so it would be good to update the compiler to the latest version. Please let me know if that solves the issue.
Best wishes,
Jan-Anton

**Comment by agkuba** [comment]
Ah, thank you! Yes, this was it. My version of Ubuntu was out of date, and my version of free pascal compiler was out of date. I had tried to update both but hadn't rebooted so it didn't take effect. Thank you so much for your help!
